remote_theme: "jekyll/minima@1e8a445"
title: Summer CS Theory Reading Group @ Purdue
description: Summer 2025 CS Theory Reading Group at Purdue University
author:
  name: Mukul Agarwal
  email: "agarw396@purdue.edu"
  
